language: node_js
node_js:
  - "9"
install:
  - npm install -g truffle
  - npm install -g ganache-cli
  - npm install
script:
  - npm lint
  - npm test
before_script:
  - testrpc > /dev/null &
  - sleep 5
after_script:
  - npm run coverage && cat coverage/lcov.info | coveralls
